apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-test
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
  - list:
      elements:
        name: karpenter-provisioner
        namespace: karpenter
        repoUrl: https://github.com/Saqeeb1234/jenkins-k8s.git
        targetRevision: main
        path: cluster-config/
  template:
    metadata:
      name: '{{name}}'
    spec:
      destination:
        namespace: '{{namespace}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: '{{path}}'
        repoURL: '{{repoURL}}'
        targetRevision: '{{revision}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true

